# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
