# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Users',
            name='nick_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
