# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0002_auto_20170704_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(default='Ukraine', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CBV_app.User'),
        ),
    ]
