# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBV_app', '0005_auto_20170707_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='position',
        ),
    ]
