# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_status',
        ),
    ]
