# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0003_userstatus_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='user_name',
            new_name='user_profile',
        ),
    ]
