# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0004_auto_20170615_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('', ''), ('vac', 'Vacation'), ('wrk', 'Working')], default='', max_length=50),
        ),
    ]
