# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_system', '0006_auto_20170615_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStatus',
            new_name='Usertatus',
        ),
    ]
